#!/bin/bash
cd $(dirname $0)

test -d tmp || mkdir tmp

GOBIN=$(pwd)/tmp go install ./gospec || exit 1 #-gcflags "-N -l" 

if [[ $1 = debug ]]; then
  dlv exec tmp/gospec "${@:1}"
else 
  tmp/gospec "${@:1}"
fi

